language: perl
perl:
  - "5.26"
  - "5.26-mb"
  - "5.24.0-thr"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"
  - "bleed"
sudo: false
matrix:
  include:
    - perl: 5.26
      env: COVERAGE=1
  allow_failures:
    - perl: bleed

before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto

install:
    - cpanm --quiet --installdeps --notest . || { cat ~/.cpanm/build.log ; false ; }
